version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - mongodb
    volumes:
      - ./backend/app:/app/app
      - ./backend/static:/app/static

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: