name: Deploy SnapEnhance-Pro Backend in Render

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Dockerfile
        run: |
          if [ ! -f backend/Dockerfile ]; then
            echo "::error::Dockerfile not found in backend folder"
            ls -la backend/
            exit 1
          fi

      - name: Build Docker Image
        working-directory: ./backend
        run: docker build -t snapenhance-backend .

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}