name: Deploy SnapEnhance-Pro Backend

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Dockerfile
        run: |
          if [ ! -f backend/Dockerfile ]; then
            echo "::error::Dockerfile not found in backend folder"
            ls -la backend/
            exit 1
          fi

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t snapenhance-backend .

      - name: Install Render CLI
        run: curl -sf https://render.com/downloads/render-cli/install.sh | bash

      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services deploy $RENDER_SERVICE_ID --api-key $RENDER_API_KEY