name: Deploy SnapEnhance-Pro Backend

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Dockerfile
        run: |
          if [ ! -f backend/Dockerfile ]; then
            echo "::error::Dockerfile not found in backend folder"
            ls -la backend/
            exit 1
          fi

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t snapenhance-backend .

      - name: Install Render CLI with retries
        run: |
          for i in {1..5}; do
            if curl -fsSL https://cli.render.com/install.sh | bash; then
              echo "$HOME/.render/bin" >> $GITHUB_PATH
              exit 0
            fi
            echo "Attempt $i failed, retrying in 5 seconds..."
            sleep 5
          done
          echo "::error::Failed to install Render CLI after 5 attempts"
          exit 1

      - name: Verify Render CLI installation
        run: |
          which render || (echo "::error::Render CLI not in PATH" && exit 1)
          render --version

      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services deploy $RENDER_SERVICE_ID --api-key $RENDER_API_KEY