name: Deploy SnapEnhance-Pro Backend

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Dockerfile
        run: |
          if [ ! -f backend/Dockerfile ]; then
            echo "::error::Dockerfile not found in backend folder"
            ls -la backend/
            exit 1
          fi

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t snapenhance-backend .

      - name: Install Render CLI (Offline Fallback)
        run: |
          # Try online installation first
          if curl -fsSL https://cli.render.com/install.sh 2>/dev/null | bash; then
            echo "$HOME/.render/bin" >> $GITHUB_PATH
          else
            # Fallback to direct download if DNS fails
            echo "::warning::Online install failed, trying direct download"
            mkdir -p $HOME/.render/bin
            curl -fL https://github.com/render-oss/cli/releases/latest/download/render-linux-amd64 -o $HOME/.render/bin/render
            chmod +x $HOME/.render/bin/render
            echo "$HOME/.render/bin" >> $GITHUB_PATH
          fi

      - name: Verify Render CLI
        run: |
          render --version || (echo "::error::Render CLI still not available" && exit 1)

      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services deploy $RENDER_SERVICE_ID --api-key $RENDER_API_KEY